[package]
name = "test-server"
version = "0.7.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false
edition = "2018"

[dependencies]
actix-http = "1.0.0"
actix-rt = "1.0.0"
actix-service = "1.0.0"
bytes = "0.5.3"
crossbeam = "0.7.3"
failure = "0.1.6"
futures = "0.3.1"
log = "0.4.8"
rand = "0.7.2"
serde_urlencoded = "0.6.1"

[dependencies.actix-web]
git = "https://github.com/actix/actix-web"
rev = "8c54054"
default-features = false

[dev-dependencies]
actix-http-test = "1.0.0"
spectral = "0.6.0"
ureq = { version = "0.11.2", default-features = false }
