[package]
name = "test-server"
version = "0.1.1"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
antidote = "*"
crossbeam-channel = "*"
iron = "*"
url = "*"

[dev-dependencies]
rand = "*"
reqwest = "*"
