[package]
name = "test-server"
version = "0.9.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false
edition = "2018"
build = "build.rs"

[dependencies]
actix-rt = "1.1.1"
actix-web = { version = "3.0.2", default-features = false }
anyhow = "1.0.32"
bytes = "0.5.6"
crossbeam-channel = "0.4.4"
futures = "0.3.5"
http = "0.2.1"
rand = "0.7.3"

[build-dependencies]
skeptic = { git = "https://github.com/budziq/rust-skeptic.git", branch = "tempfile" }

[dev-dependencies]
skeptic = { git = "https://github.com/budziq/rust-skeptic.git", branch = "tempfile" }
ureq = { version = "1.4.1", default-features = false }
