[package]
name = "test-server"
version = "0.3.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
antidote = "1.0.0"
bytes = "0.4.9"
crossbeam-channel = "0.2.2"
futures = "0.1.21"
lazy_static = "1.1.0"
rand = "0.5.5"

[dependencies.actix-web]
version = "0.7.3"
default-features = false

[dev-dependencies]
reqwest = "0.8.6"
