[package]
name = "test-server"
version = "0.7.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false
edition = "2018"

[dependencies]
actix-http = "0.2.11"
actix-rt = "0.2.6"
actix-service = "0.4.2"
bytes = "0.4.12"
crossbeam = "0.7.3"
failure = "0.1.6"
futures = "0.1.29"
log = "0.4.8"
rand = "0.7.2"
serde_urlencoded = "0.6.1"

[dependencies.actix-web]
version = "1.0.9"
default-features = false

[dev-dependencies]
actix-http-test = "0.2.5"
spectral = "0.6.0"
ureq = { version = "0.11.2", default-features = false }
