[package]
name = "test-server"
version = "0.7.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = { version = "2.0.0", default-features = false }
bytes = "0.5.3"
crossbeam-channel = "0.4.0"
failure = "0.1.6"
futures = "0.3.1"
http = "0.2.0"
rand = "0.7.2"

[dev-dependencies]
ureq = { version = "0.11.2", default-features = false }
