[package]
name = "test-server"
version = "0.5.1"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
bytes = "0.4.9"
crossbeam-channel = "0.2.4"
futures = "0.1.23"
rand = "0.5.5"

[dependencies.actix-web]
version = "0.7.5"
default-features = false

[dev-dependencies]
reqwest = "0.8.8"
spectral = "0.6.0"
