[package]
name = "test-server"
version = "0.5.3"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
actix-net = "0.2.2"
bytes = "0.4.10"
crossbeam-channel = "0.3.1"
futures = "0.1.25"
rand = "0.6.0"

[dependencies.actix-web]
version = "0.7.14"
default-features = false

[dev-dependencies]
reqwest = "0.9.5"
spectral = "0.6.0"
