[package]
name = "test-server"
version = "0.2.2"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
actix = "0.5.8"
crossbeam-channel = "0.2.2"
futures = "0.1.21"

[dependencies.actix-web]
version = "0.6.15"
default-features = false

[dev-dependencies]
rand = "0.5.4"
reqwest = "0.8.6"
