[package]
name = "test-server"
version = "0.1.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
spmc = "0.2"
