[package]
name = "test-server"
version = "0.5.2"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false

[dependencies]
bytes = "0.4.10"
crossbeam-channel = "0.2.6"
futures = "0.1.24"
rand = "0.5.5"

[dependencies.actix-web]
version = "0.7.8"
default-features = false

[dev-dependencies]
reqwest = "0.9.2"
spectral = "0.6.0"
