[package]
name = "test-server"
version = "0.6.0"
authors = ["Christian Fochler <mail@christianfochler.de>"]
license = "MIT"
repository = "https://github.com/ChriFo/test-server-rs"
publish = false
edition = "2018"

[dependencies]
actix-http = "0.2.4"
actix-rt = "0.2.3"
actix-service = "0.4.1"
bytes = "0.4.12"
crossbeam-channel = "0.3.8"
failure = "0.1.5"
futures = "0.1.27"
rand = "0.6.5"
serde_urlencoded = "0.5.5"
tokio-current-thread = "0.1.6"

[dependencies.actix-web]
version = "1.0.2"
default-features = false

[dev-dependencies]
log = "0.4.6"
reqwest = "0.9.18"
spectral = "0.6.0"
