sign-commit = true
disable-push = true
upload-doc = false
no-dev-version = true
tag-message = "{{version}}"
tag-prefix = "v"
pre-release-commit-message = "{{version}}"
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="README.md", search="tag = \"v[0-9\\.]+\"", replace="tag = \"v{{version}}\""},
]